install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev git libxcb1-dev libxcb-keysyms1-dev python python-pip

before_script:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --set g++ /usr/bin/g++-4.8
    - curl http://clipperapp.tk/static/build/qpa.tar.gz > qpa.tar.gz
    - gunzip ./qpa.tar.gz
    - tar -xvf ./qpa.tar
    - sudo mv qpa /usr/include/qt5/QtGui/qpa
    - sudo pip install requests

script:
    - cd src
    - git clone https://github.com/falceeffect/UGlobalHotkey.git ./libs/UGlobalHotkey/UGlobalHotkey
    - cd ./libs/UGlobalHotkey
    - qmake -qt=qt5 ./UGlobalHotkey/uglobalhotkey.pro
    - make
    - cd ..
    - cd ..
    - qmake -qt=qt5 ./Clipper.pro
    - make
    - curl http://clipperapp.tk/static/build/build-package.sh > build-package.sh
    - curl http://clipperapp.tk/static/build/description-pak > description-pak
    - curl http://clipperapp.tk/static/build/dropbox-upload.py > dropbox-upload.py
    - sudo chmod +x build-package.sh
    - sudo chmod +x dropbox-upload.py
    - ./build-package.sh
    - python ./dropbox-upload.py clipper_1.3-1_amd64.deb